- hosts: localhost
  tasks:
    - name: "Create content view"
      redhat.satellite.content_view:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        organization: "{{ organization }}"

        name: RHEL9
        repositories:
        - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9'
          product: 'Red Hat Enterprise Linux for x86_64'
        - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9'
          product: 'Red Hat Enterprise Linux for x86_64'

        - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9.2'
          product: 'Red Hat Enterprise Linux for x86_64'
        - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9.2'
          product: 'Red Hat Enterprise Linux for x86_64'

        - name: 'Red Hat Ansible Automation Platform 2.5 for RHEL 9 x86_64 RPMs'
          product: 'Red Hat Ansible Automation Platform'



