- hosts: localhost
  tasks:

  - name: "Create a product for EPEL"
    redhat.satellite.product:
      username: "{{ username }}"
      password: "{{ password }}"
      server_url: "{{ server_url }}"
      organization: "{{ organization }}"   

      name: "EPEL 9"
      state: present

